name: Setup

inputs:
  anio-pkey:
    required: true
  anio-cert:
    required: true
  anio-registry-token:
    required: true
  npm-token:
    required: true

runs:
  using: "composite"
  steps:
    # Place private key and certificate in order to have
    # access to npm-registry.anio.software
    - name: "Setup runner private key and certificate"
      env:
        ANIO_NPM_REGISTRY_GITHUB_CICD_CERT: ${{ inputs.anio-cert }}
        ANIO_NPM_REGISTRY_GITHUB_CICD_PKEY: ${{ inputs.anio-pkey }}
      run: |
        touch ./.cicd/client.cert
        touch ./.cicd/client.pkey
        chmod 0600 ./.cicd/client.cert ./.cicd/client.pkey
        printf "%s" "$ANIO_NPM_REGISTRY_GITHUB_CICD_CERT" > ./.cicd/client.cert
        printf "%s" "$ANIO_NPM_REGISTRY_GITHUB_CICD_PKEY" > ./.cicd/client.pkey
        openssl x509 -in ./.cicd/client.cert -noout -text

    - name: "Setup npmrc file"
      run: |
        printf "" > ./.cicd/npmrc

        printf "%s\n" "registry=https://registry.npmjs.org" >> ./.cicd/npmrc
        printf "%s\n" "@asint:registry=https://npm-registry.anio.software" >> ./.cicd/npmrc
        printf "%s\n" "@asint-types:registry=https://npm-registry.anio.software" >> ./.cicd/npmrc
        printf "%s\n" "//npm-registry.anio.software/:keyfile=../../.cicd/client.pkey" >> ./.cicd/npmrc
        printf "%s\n" "//npm-registry.anio.software/:certfile=../../.cicd/client.cert" >> ./.cicd/npmrc

        if [[ "${{ github.ref_name }}" == vp* ]]; then
          printf "%s\n" "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" >> ./.cicd/npmrc
        else
          printf "%s\n" "//npm-registry.anio.software/:_authToken=${{ inputs.anio-registry-token }}" >> ./.cicd/npmrc
        fi
