import {
	createConfig,
	createTargetJSNodeOptions,
	createAutogeneratedFile
} from "enkore/spec/factory"

export const config: unknown = createConfig({
	target: {
		name: "js-node",
		options: createTargetJSNodeOptions({
			// needed or we end up with a broken build
			preprocess: {
				expandStarExports: true
			},
			publish: {
				withExactDependencyVersions: true,
				withPackageNames: [
					"@enkore-toolchain/js-none",
					"@enkore-toolchain/js-node",
					"@enkore-toolchain/js-web"
				]
			},
			createTypesPackage: {
				orgName: "@enkore-toolchain-types"
			},
			externalPackages: [
				"@enkore-private/target-js-typescript",
				"@enkore-private/target-js-babel",
				"@enkore-private/target-js-rollup"
			]
		})
	},

	autogeneratedFiles: [
		createAutogeneratedFile({
			destinationPath: "project/export/toolchainRev.mts",
			generator(session) {
				const {version} = session.project.packageJSON
				const [major, minor, patch] = version.split(".").map(part => {
					return parseInt(part, 10)
				})

				let revision = patch

				revision += (minor * 1000)
				revision += (major * 1000000)

				return `export const toolchainRev = ${revision};\n`
			}
		})
	]
})
